global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'microservices'
    static_configs:
      - targets:
          - 'auth:8080'
          - 'stream-line:8080'
          - 'forms:8080'
          - 'profile:8080'
          - 'question:8080'
          

  - job_name: 'postgres'
    static_configs:
      - targets:
          - 'postgres:5432'

  - job_name: 'kafka'
    static_configs:
      - targets:
          - 'kafka:9092'